## Assignment #1

* Release date: 2021.03.29 Mon
* Due date: **2021.04.04 Sun 23:59** (will not accept late submission)
* Submission format: notebook file which can be executed in Colab environment
* Weighting: 5% (total 50 pts)

1. **(10pts)** Calculate `rotation*x` and `x*rotation`. Explain how each computation is performed and why two results are the same.

  ```python
    import numpy as np

    x = np.array([[2, 0]])
    rotation = np.array([ [0, -1],
                          [1,  0] ])
  ```

In [ ]:
import numpy as np
 
x = np.array([2,0])
rotation = np.array([[0,-1],
                    [1,0]])

z1 = rotation*x
z2 = x*rotation

print(z1)
print(z2)


[[0 0]
 [2 0]]
[[0 0]
 [2 0]]


'*' funtion is element-wise multiplication  funtion. 

so in this cace, the sequence of the variables isn't matter

2. **(10pts)** Suppose we have the following 2D tensor (i.e., a matrix). How to rearrange its values into 1D tensor (i.e., a vector) in a column major order?
```python
x = np.array([[1,  2,  3,  4],
                 [5,  6,  7,  8],
                 [9, 10, 11, 12]])
```

In [ ]:
x = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])
x = x.reshape((12))
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


3. **(10pts)** Compute a transpose of the matrix `x` in Problem 2 by using only `np.reshape` function.

In [ ]:
x = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])

x1 = x.transpose()
print(x1)

x = x.reshape((12))
print(x)

x = x.reshape((4,3), order='F')
print(x)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


4. **(10pts)** Given any random matrices, compute the element-wise multiplication using a naive Python implementation and Numpy built-in function respectively. Compare the wall-clock times of these implementations as the size of matrices increases.



In [ ]:
import time


for i in range(2,1000):
  start = time.time()
  x1=np.random.randint(10, size=(i, i))
  

  x2=np.random.randint(10, size=(i, i))
  

  x3 = x1* x2

  
  elapsed = time.time() - start


  print('Time taken to multiply two (%d,%d) matrices  : %.12f' % (i,i,elapsed))


The larger the matrix is, the greater the wall-clock time.

5. **(10pts)** Consider MNIST classification problem covered during the class. For the details, please refer to the course material. In this example, we used the multilayer perceptron composed of an input layer with 512 hidden nodes and an output layer that produces predicted probabilities over 10 classes. In the class, we used GPU as a hardware accelerator to train our model.

  Here, let's verify the actual benefit of using GPU for training. For this, compare the wall-clock times in the case of 1) using CPU and 2) using GPU to train MNIST classifier.


Epoch 1/5
469/469 [==============================] - 1s 3ms/step - loss: 0.0281 - accuracy: 0.9916
Epoch 2/5
469/469 [==============================] - 1s 2ms/step - loss: 0.0214 - accuracy: 0.9936
Epoch 3/5
469/469 [==============================] - 1s 2ms/step - loss: 0.0166 - accuracy: 0.9949
Epoch 4/5
469/469 [==============================] - 1s 2ms/step - loss: 0.0133 - accuracy: 0.9963
Epoch 5/5
469/469 [==============================] - 1s 2ms/step - loss: 0.0098 - accuracy: 0.9974
Elapsed time: 5.8879


this is the wall-clock time when use GPU


Epoch 1/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0283 - accuracy: 0.9917
Epoch 2/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0219 - accuracy: 0.9939
Epoch 3/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0172 - accuracy: 0.9947
Epoch 4/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0137 - accuracy: 0.9961
Epoch 5/5
469/469 [==============================] - 5s 11ms/step - loss: 0.0100 - accuracy: 0.9973
Elapsed time: 24.4640

this is the wall-clock time when use CPU